# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('capacity', models.IntegerField()),
                ('activity_level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('next_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Period')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proximity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_locations', to='infrastructure.Activity')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='infrastructure.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('activities', models.ManyToManyField(blank=True, to='infrastructure.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='availability',
            field=models.ManyToManyField(blank=True, to='infrastructure.Period'),
        ),
        migrations.AddField(
            model_name='activity',
            name='proximity',
            field=models.ManyToManyField(related_name='seperated_by', through='infrastructure.Proximity', to='infrastructure.Activity'),
        ),
    ]
