# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proximity',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='proximity',
            name='start_point',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='proximity',
        ),
        migrations.AddField(
            model_name='zone',
            name='adjacent_zones',
            field=models.ManyToManyField(blank=True, related_name='_zone_adjacent_zones_+', to='infrastructure.Zone'),
        ),
        migrations.DeleteModel(
            name='Proximity',
        ),
    ]
