# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abscence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('activity', models.ManyToManyField(blank=True, to='infrastructure.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('qualifications', models.ManyToManyField(blank=True, to='infrastructure.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, to='operations.Group')),
                ('guests', models.ManyToManyField(blank=True, to='operations.Guest')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.ProgramType')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='guests',
            field=models.ManyToManyField(blank=True, to='operations.Guest'),
        ),
        migrations.AddField(
            model_name='abscence',
            name='employee',
            field=models.ManyToManyField(blank=True, to='operations.Employee'),
        ),
    ]
