# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Activity')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Group')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Period')),
            ],
        ),
        migrations.CreateModel(
            name='Floater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Activity')),
                ('floater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Group')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Employee')),
            ],
        ),
    ]
