# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('scheduler', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Employee')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.Program')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupleader',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupleader',
            name='leader',
        ),
        migrations.AddField(
            model_name='assigment',
            name='crew',
            field=models.ManyToManyField(blank=True, to='operations.Employee'),
        ),
        migrations.DeleteModel(
            name='GroupLeader',
        ),
    ]
